// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RankingService.Data;

namespace RankingService.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RankingService.Entities.Rate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RateScale")
                        .HasColumnType("int");

                    b.Property<Guid>("RateTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RateTypeId");

                    b.ToTable("Rate");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Rate");
                });

            modelBuilder.Entity("RankingService.Entities.RateType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RateTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RateTypes");
                });

            modelBuilder.Entity("RankingService.Entities.PostRate", b =>
                {
                    b.HasBaseType("RankingService.Entities.Rate");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("PostRate");
                });

            modelBuilder.Entity("RankingService.Entities.TransportRate", b =>
                {
                    b.HasBaseType("RankingService.Entities.Rate");

                    b.Property<int>("TransportId")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("TransportRate");
                });

            modelBuilder.Entity("RankingService.Entities.UserRate", b =>
                {
                    b.HasBaseType("RankingService.Entities.Rate");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("UserRate");
                });

            modelBuilder.Entity("RankingService.Entities.Rate", b =>
                {
                    b.HasOne("RankingService.Entities.RateType", "RateType")
                        .WithMany("Rates")
                        .HasForeignKey("RateTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RateType");
                });

            modelBuilder.Entity("RankingService.Entities.RateType", b =>
                {
                    b.Navigation("Rates");
                });
#pragma warning restore 612, 618
        }
    }
}
